#!/bin/sh
#/etc/init.d/SICKinit

### BEGIN INIT INFO
# Provides:          SICKinit
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:
### END INIT INFO

case "$1" in
    start)
       /home/pi/git/RasPI_and_robots/shutdown_RPi.py &
       /home/pi/git/RasPI_and_robots/init.sh
        ;;
    stop)
        killall init.sh
        ;;
    *)
        exit 1
        ;;
esac

exit 0
